# Site settings
title: Blog
email: adhyan2095@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  keep Trying! Keep Learnng! Follow your dreams ;)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ad-os.github.io" # the base hostname & protocol for your site
twitter_username: "@tech_adhyan"
github_username:  ad-os
permalink: /blog/:title

# Build settings
markdown: kramdown
