#!/usr/bin/env python
 
import SocketServer
from SimpleHTTPServer import SimpleHTTPRequestHandler
 
class http_handler(SimpleHTTPRequestHandler):
    pass
 
class TCPServer(SocketServer.TCPServer):
    """
    this is a variable that may be overridden by derived classes or
    instances
    i found it at '/usr/lib/python2.7/SocketServer.py'
    """
    allow_reuse_address = True
 
server_addr = ('127.0.0.1',8000)
httpd = TCPServer(server_addr, http_handler)
print "listening on: %s:%d" % (server_addr[0], server_addr[1])
httpd.serve_forever()
